// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboil0KDbD9GUl1czndRVlsq_faLnc2wE',
    appId: '1:1026309586978:web:026ff20ea7ade4aa0a0a7b',
    messagingSenderId: '1026309586978',
    projectId: 'reddit-clone-tutorial-25deb',
    authDomain: 'reddit-clone-tutorial-25deb.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-25deb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnmilulxP5EtWYYzSuaVQXi8whTY8aY5g',
    appId: '1:1026309586978:android:3c1b23f5a0e547060a0a7b',
    messagingSenderId: '1026309586978',
    projectId: 'reddit-clone-tutorial-25deb',
    storageBucket: 'reddit-clone-tutorial-25deb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_n18rfDiMka1oVRKqh_kBDGq97hsH_ks',
    appId: '1:1026309586978:ios:6d25bbe38da965310a0a7b',
    messagingSenderId: '1026309586978',
    projectId: 'reddit-clone-tutorial-25deb',
    storageBucket: 'reddit-clone-tutorial-25deb.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
